# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Noah Prescott
email: hello@noahprescott.com
description: > # this means to ignore newlines until "baseurl:"
  Come out to the coast, we'll get together, have a few laughs.
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  npresco

# Build settings
markdown: kramdown
